version: 0.2
            
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g serverless@1.51.0
  build:
    commands:
      - serverless deploy --stage {STAGE} --verbose --force
      - (cd ./infrastructure && serverless deploy --stage {STAGE} --verbose --force)
