service: infrastructure 

frameworkVersion: '>=1.50.0'

provider:
  name: aws
  stackName: ${self:custom.config.stack_name}
  stage: ${self:custom.stage}
  region: us-east-2

custom:
  stage: ${opt:stage, 'dev'}
  config:
    stack_name: ${self:service}-${self:custom.stage}
    table_name: summit-table
    dev:
      read_capacity_units: 1
      write_capacity_units: 1
    prod:
      read_capacity_units: 2
      write_capacity_units: 2

resources:
- ${file(table.yaml)}